version: "3"

services:
  back:
    build: ./back/
    container_name: website-back
    restart: always
    volumes:
      - ./back:/app
    ports:
      - "4000:4000"
      - "81:81"
    environment:
      PORT: 4000
      FORTYTWO_OAUTH_UID: <42 oauth uid>
      FORTYTWO_OAUTH_SECRET: <42 oauth secret>
      JWT_SECRET: <generate a secret pass>
    command: "yarn start:dev"
    depends_on:
      - db
  front:
    build: ./front/
    container_name: website-front
    restart: always
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    environment:
      BROWSER_BACKEND_BASE_URL: http://localhost:4000
      SSR_BACKEND_BASE_URL: http://back:4000
    command: "yarn dev"
    depends_on:
      - back
  db:
    image: postgres
    volumes:
      - ./postgres/.tmp/db:/var/lib/postgresql/data
      - ./postgres/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /tmp
